CREATE TABLE `customer` (
  `CUST_ID` int NOT NULL AUTO_INCREMENT,
  `FULL_NAME` varchar(45) COLLATE utf8_bin DEFAULT NULL,
  `EMAIL` varchar(45) COLLATE utf8_bin DEFAULT NULL,
  `PH_NUM` varchar(45) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`CUST_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `customer_address` (
  `CUST_ADDR_ID` int NOT NULL AUTO_INCREMENT,
  `CUST_ID` int NOT NULL,
  `ADDR_TYPE` varchar(45) COLLATE utf8_bin NOT NULL,
  `HOUSE_NUM` varchar(45) COLLATE utf8_bin DEFAULT NULL,
  `STREET` varchar(45) COLLATE utf8_bin DEFAULT NULL,
  `ZIP_CODE` varchar(45) COLLATE utf8_bin DEFAULT NULL,
  `CITY` varchar(45) COLLATE utf8_bin DEFAULT NULL,
  `DISTRICT` varchar(45) COLLATE utf8_bin DEFAULT NULL,
  `STATE` varchar(45) COLLATE utf8_bin DEFAULT NULL,
  `COUNTRY` varchar(45) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`CUST_ADDR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
